/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotdemo

import org.kodein.di.DI
import org.kodein.di.bindSingleton

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }

    private fun buildDIModule() = DI.Module("App") {
        bindSingleton{ SomeObject("Hello Message") }
    }

    // I've read the docs and looks at examples, but have no idea how this is working.
    // Managed to copy and paste some code
    fun buildDIContainer() = DI {
        import(buildDIModule())
    }

}

fun main() {
    val app = App()
    println(app.greeting)


    val kodein = app.buildDIContainer()
    val diExample: DIExample = DIExample(kodein)
    diExample.printTheObjectMessage()
}
